### ISSUE TITLE
Usage doc confusion

### ISSUE THREAD

**Issue by limscoder** [lucasconstantino/redux-transient#3]
The docs contain this usage:

```javascript
import { enhancer } from 'redux-transient'
const store = createStore(reducers, 0, enhancer)
```

This did not seem to work with composed enhancers:

```javascript
import { enhancer as transientEnhancer } from 'redux-transient'

const combinedEnhancer = compose(transientEnhancer, otherEnhancer);
const store = createStore(reducers, 0, combinedEnhancer)
```

Reading the code, it appears this is the way to use the enhance function, which does work for me:

```javascript
transientEnhancer(createStore)(reducer, initialState, otherEnhancer);
```

**Comment by lucasconstantino** [comment]
I've [added a test](https://github.com/lucasconstantino/redux-transient/blob/master/__tests__/transient-enhancer.js#L195) which covers usage with `applyMiddleware`. This test should serve as an example on how to integrate `redux-transient` with any other enhancers out there. In fact, `transientEnhancer` implements the a transparent enhancer, meaning it will virtually have no effect on other enhancers in the cycle.

**Comment by limscoder** [comment]
thanks!

**Comment by limscoder** [comment]
I figured out my issue. The transientEnhance had to go first within `compose` so that the transient logic gets executed before the other enhancers/middleware.

**Comment by lucasconstantino** [comment]
That is not necessarily true to all. In my tests, using `applyMiddleare`, I've place it both before and after and it worked as expected.

Could you tell me which enhancer are you using in combination with transient?
